Repository 254Labs/awesome-bambdas, pull requests merged in 2023-12, with the labels that each got.

#5 Converted Bambdas to Markdown and added GitHub Pages Draft
  .github/ISSUE_TEMPLATE/pull_request.md
  .gitignore
  404.html
  CONTRIBUTING.md
  Dockerfile
  Gemfile
  Gemfile.lock
  Makefile
  README.md
  _config.yml
  _sass/custom/custom.scss
  assets/images/favicon.ico
  assets/images/usage.png
  docs/_bambda.md.template
  docs/request/.gitkeep
  docs/request/after_datetime.md
  docs/request/before_datetime.md
  docs/request/index.md
  docs/request/only_with_response.md
  docs/request/owasp_top25.md
  docs/request/with_specific_cookie.md
  docs/response/.gitkeep
  docs/response/basic_json_filter.md
  docs/response/cacheable.md
  docs/response/diff_content_length.md
  docs/response/index.md
  docs/response/js_files_content_type.md
  docs/response/json_w_content_type_mismatch.md
  docs/response/potential_redirects_302.md
  docs/response/redirection_w_specific_cookie.md
  docs/response/role_claim_jwt.md
  docs/response/uid_for_rce.md
  docs/utilities/.gitkeep
  docs/utilities/coloring.md
  docs/utilities/index.md
Labels: documentation

#7 Update README.md
  README.md
Labels: readme-update

#11 Update diff-content-length.java
  response-filters/diff-content-length.java
Labels: fix-typo

#9 Update find-uid-for-rce-vuln.java
  response-filters/find-uid-for-rce-vuln.java
Labels: fix-typo
